### ISSUE TITLE
Appropriate observation space?

### ISSUE THREAD

**Issue by josephch405** [SeanBae/gym-snake#1]
Happened to stumble upon this environment while I was looking to try out the OpenAI challenges. Is development for this environment still going on? Would love to work together on this.

Seems like the next step is to provide an appropriate observation space such that we can actually make agents that respond to it. I'm thinking either a fully representative grid of the entire game, or perhaps a constricted view from the head of the snake (which may generalize better for differently sized maps).

**Comment by SeanBae** [comment]
@josephch405 Thanks for reaching out, and I'm happy to work together! 😄

You have some good points, and I agree that both of the observation spaces might be worth exploring. It's not immediately clear to me what kind of spaces we can use to robustly represent the constricted view, but I'm happy to brainstorm if you have some ideas.

In the meantime, let's prioritize on building the full grid approach first, because it's straight-forward and [simple to implement](https://github.com/openai/gym/tree/master/gym/spaces).

I can work on this some time next week, but I'm also happy to create and assign a ticket to you if you want to take this on.

Lemme know!
